name: Express Server CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Stop existing Node.js process
        run: |
          set -e
          PID=$(lsof -ti :3000 || true)
          if [ ! -z "$PID" ]; then
            echo "Stopping existing Node.js process..."
            kill $PID || true
          else
            echo "No existing Node.js process found."
          fi
      - name: Deploy
        run: echo "Deploying to production server..."
      - name: Start new process
        run: nohup npm start > /dev/null 2>&1 &